### ISSUE TITLE
[Fancy Block Placement] Rapid placing blocks crash NPE: `at net.minecraft.inventory.Slot.putStack`

### ISSUE THREAD

**Issue by Krutoy242** [Red-Studio-Ragnarok/Fancier-Block-Particles#14]
## Describe the bug

After [this issue](https://github.com/Red-Studio-Ragnarok/Fancier-Block-Particles/issues/13) was fixed, i tested is everything continue working.

When I hold right-click and run, placing Mek Cubes, on moment 6th cube should be placed game crashed.

I tested this issue two times.

![dwm_Ga6JsoaWzd](https://user-images.githubusercontent.com/936618/209547286-cf2332b4-7494-4917-81e9-e7ca70205c68.png)

![dwm_Gus7sXUhx7](https://user-images.githubusercontent.com/936618/209547307-556d7c6f-424e-466b-bbef-3e5dfbfdf729.png)

## Additional info

- FBP version: `0.8-Dev-10`
- Optifine NOT installed

## Log

```less
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:6614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.inventory.Slot.putStack(Slot.java:70)
    at net.minecraft.inventory.Container.setAll(Container.java:527)
    at net.minecraft.client.network.NetHandlerPlayClient.handleWindowItems(NetHandlerPlayClient.java:1191)
    at net.minecraft.network.play.server.SPacketWindowItems.processPacket(SourceFile:50)
    at net.minecraft.network.play.server.SPacketWindowItems.processPacket(SourceFile:12)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more
```

[debug.log](https://github.com/Red-Studio-Ragnarok/Fancier-Block-Particles/files/10303345/debug.log)

**Comment by JustDesoroxxx** [comment]
Pretty sure mekanism playing with multithreading can you test without FBP if this issue happens

**Comment by Krutoy242** [comment]
I tested: without FBP this issue not happen.

**Comment by JustDesoroxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project: Pacificus Ponens](https://trello.com/c/z0pwdSCv/48-project-pacificus-ponens)
