### ISSUE TITLE
Crash in `AnimationDummyBlock`

### ISSUE THREAD

**Issue by Krutoy242** [Red-Studio-Ragnarok/Fancier-Block-Particles#18]
Rapid placing Snow Layers on snow causing freeze of game and crash.

The reproduce steps are similar to other issue: https://github.com/Red-Studio-Ragnarok/Fancier-Block-Particles/issues/13 - i just hold right mouse button.

```less
Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@1387c55:
java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=layers, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7, 8]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209) ~[awu$a.class:?]
	at snownee.snow.ModSnowBlock.isReplaceable(ModSnowBlock.java:395) ~[ModSnowBlock.class:?]
	at io.redstudioragnarok.FBP.handler.EventHandler.onInteractionEvent(EventHandler.java:262) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4626_EventHandler_onInteractionEvent_RightClickBlock.invoke(.dynamic) ~[?:?]
```

![dwm_Lf5HfxCEJ3](https://user-images.githubusercontent.com/936618/210167839-11da5a16-516d-470d-bc18-e39a6fcf7e9b.png)
[debug.log](https://github.com/Red-Studio-Ragnarok/Fancier-Block-Particles/files/10328624/debug.log)

<details>
  <summary>Additional context</summary>  

	Version: Fancier-Block-Particles-0.8-Dev-10
	SnowRealMagic-1.12.2-0.6.2
  
	Happen on E2E-E modpack https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended
    
	- OS: Windows 10
	- CPU: i5-7400 @ 3.00 GHz
	- GPU: GTX 1050 Ti
	- RAM Allocated: 6GB
  
</details>

**Comment by JustDesoroxxx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project: Pacificus Ponens](https://trello.com/c/z0pwdSCv/48-project-pacificus-ponens)

**Comment by JustDesoroxxx** [comment]
Update

I have discovered that the crash is simply due to snow being placed on snow while animating.

This will be fixed when the Pacificus Poens project is done, as well as a ton of other issues.
